name: build

on: push

jobs:
  linux:
    name: Build (Linux)
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Print Go Environment
        run: go env

      - name: Install GoCV
        run: go get -u -d gocv.io/x/gocv

      - name: Install OpenCV
        run: cd $GOPATH/src/gocv.io/x/gocv && make install

      - name: Test GoCV
        run: cd $GOPATH/src/gocv.io/x/gocv && go run ./cmd/version/main.go

      - name: Install Tesseract
        run: sudo apt -y install tesseract-ocr libtesseract-dev

      - name: Test
        run: go run .
